name: Pipeline execução dos testes em Playwright
on:
  push:
    branches: [main, master, qa-play]
  pull-request:
    branches: [main, master]
jobs:
  tests:
    name: Playwrigth Tests
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Checkout repository
        uses: actions/checkout@v3
      - name: Step 2 - Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Step 3 - Install Dependences
        run: npm install
      - name: Step 4 -Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Step 5 - Up environment HML WEB
        run: npm run start && echo 1
      - name: Step 6 - Up environment HML API
        run: npm run start && echo 2
      - name: Step 7 - Run tests Playwritght
        run: npx playwright test
      - name: Gerando artifacts / Logs
        uses: actions/upload-artifact@v3
        with:
          path: playwright-report/